// Package export writes session scrollback history to a Markdown bundle.
//
// The output directory contains:
//
//	session.md          — full multi-window export
//	assets/             — binary image files referenced by the Markdown
//
// Markdown structure:
//
//	# Window: build
//
//	## Pane: build-log
//
//	<scrollback lines>
//
//	## Pane: build-errors
//	...
package export

import (
	"encoding/base64"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// PaneExport holds the data for one pane's export.
type PaneExport struct {
	TargetID string
	Lines    []string
}

// WindowExport holds the data for one window's export.
type WindowExport struct {
	Name  string
	Panes []PaneExport
}

// Bundle writes a Markdown file and assets directory to outDir.
// filename is the name of the Markdown file (e.g. "session.md").
func Bundle(windows []WindowExport, outDir, filename string) error {
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return fmt.Errorf("creating output directory %q: %w", outDir, err)
	}

	assetsDir := filepath.Join(outDir, "assets")
	if err := os.MkdirAll(assetsDir, 0755); err != nil {
		return fmt.Errorf("creating assets directory: %w", err)
	}

	var sb strings.Builder
	sb.WriteString("<!-- Generated by rdw at " + time.Now().UTC().Format(time.RFC3339) + " -->\n\n")

	imageCounter := 0

	for _, win := range windows {
		sb.WriteString("# Window: " + win.Name + "\n\n")

		for _, pane := range win.Panes {
			sb.WriteString("## Pane: " + pane.TargetID + "\n\n")
			sb.WriteString("```\n")

			for _, line := range pane.Lines {
				// Detect base64-encoded image lines and extract to assets/.
				if strings.HasPrefix(line, "b64:") {
					imageCounter++
					decoded, err := base64.StdEncoding.DecodeString(line[4:])
					if err == nil {
						ext  := sniffImageExt(decoded)
						name := fmt.Sprintf("image-%04d%s", imageCounter, ext)
						path := filepath.Join(assetsDir, name)
						if writeErr := os.WriteFile(path, decoded, 0644); writeErr == nil {
							sb.WriteString("```\n\n")
							sb.WriteString("![" + pane.TargetID + "](assets/" + name + ")\n\n")
							sb.WriteString("```\n")
							continue
						}
					}
					// Couldn't decode/write — emit raw.
					sb.WriteString(line + "\n")
					continue
				}

				// Strip ANSI escape sequences for plain Markdown.
				sb.WriteString(stripANSI(line) + "\n")
			}

			sb.WriteString("```\n\n")
		}
	}

	mdPath := filepath.Join(outDir, filename)
	if err := os.WriteFile(mdPath, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("writing %q: %w", mdPath, err)
	}

	return nil
}

// sniffImageExt returns a file extension based on magic bytes.
func sniffImageExt(data []byte) string {
	if len(data) < 4 {
		return ".bin"
	}
	// PNG: \x89PNG
	if data[0] == 0x89 && data[1] == 'P' && data[2] == 'N' && data[3] == 'G' {
		return ".png"
	}
	// JPEG: \xFF\xD8
	if data[0] == 0xFF && data[1] == 0xD8 {
		return ".jpg"
	}
	// SVG: starts with < (XML)
	if data[0] == '<' {
		return ".svg"
	}
	// GIF: GIF8
	if len(data) >= 6 && string(data[:4]) == "GIF8" {
		return ".gif"
	}
	return ".bin"
}

// stripANSI removes ANSI escape sequences from a string.
func stripANSI(s string) string {
	var out strings.Builder
	i := 0
	for i < len(s) {
		if s[i] == '\x1b' && i+1 < len(s) && s[i+1] == '[' {
			// Skip until 'm' or other terminator.
			i += 2
			for i < len(s) && !isANSITerminator(s[i]) {
				i++
			}
			if i < len(s) {
				i++ // skip terminator
			}
			continue
		}
		out.WriteByte(s[i])
		i++
	}
	return out.String()
}

func isANSITerminator(c byte) bool {
	return c >= 0x40 && c <= 0x7E
}
