package export_test

import (
	"encoding/base64"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/nkh/rdw/internal/export"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestBundle_CreatesMarkdownFile(t *testing.T) {
	outDir := t.TempDir()
	windows := []export.WindowExport{
		{
			Name: "build",
			Panes: []export.PaneExport{
				{TargetID: "stdout", Lines: []string{"line1", "line2"}},
			},
		},
	}

	err := export.Bundle(windows, outDir, "session.md")
	require.NoError(t, err)

	data, err := os.ReadFile(filepath.Join(outDir, "session.md"))
	require.NoError(t, err)
	content := string(data)

	assert.Contains(t, content, "# Window: build")
	assert.Contains(t, content, "## Pane: stdout")
	assert.Contains(t, content, "line1")
	assert.Contains(t, content, "line2")
}

func TestBundle_CreatesAssetsDir(t *testing.T) {
	outDir := t.TempDir()
	err := export.Bundle([]export.WindowExport{{Name: "w", Panes: []export.PaneExport{}}},
		outDir, "out.md")
	require.NoError(t, err)

	info, err := os.Stat(filepath.Join(outDir, "assets"))
	require.NoError(t, err)
	assert.True(t, info.IsDir())
}

func TestBundle_MultipleWindows(t *testing.T) {
	outDir := t.TempDir()
	windows := []export.WindowExport{
		{Name: "build", Panes: []export.PaneExport{{TargetID: "log", Lines: []string{"a"}}}},
		{Name: "metrics", Panes: []export.PaneExport{{TargetID: "cpu", Lines: []string{"b"}}}},
	}

	require.NoError(t, export.Bundle(windows, outDir, "session.md"))

	data, _ := os.ReadFile(filepath.Join(outDir, "session.md"))
	content := string(data)
	assert.Contains(t, content, "# Window: build")
	assert.Contains(t, content, "# Window: metrics")
}

func TestBundle_MultiplePanesPerWindow(t *testing.T) {
	outDir := t.TempDir()
	windows := []export.WindowExport{
		{
			Name: "ci",
			Panes: []export.PaneExport{
				{TargetID: "stdout", Lines: []string{"out"}},
				{TargetID: "stderr", Lines: []string{"err"}},
			},
		},
	}

	require.NoError(t, export.Bundle(windows, outDir, "out.md"))
	data, _ := os.ReadFile(filepath.Join(outDir, "out.md"))
	content := string(data)
	assert.Contains(t, content, "## Pane: stdout")
	assert.Contains(t, content, "## Pane: stderr")
}

func TestBundle_StripANSI(t *testing.T) {
	outDir := t.TempDir()
	windows := []export.WindowExport{
		{Name: "w", Panes: []export.PaneExport{
			{TargetID: "p", Lines: []string{"\x1b[32mgreen text\x1b[0m"}},
		}},
	}

	require.NoError(t, export.Bundle(windows, outDir, "out.md"))
	data, _ := os.ReadFile(filepath.Join(outDir, "out.md"))
	content := string(data)

	assert.Contains(t, content, "green text")
	assert.NotContains(t, content, "\x1b[")
}

func TestBundle_Base64Image_ExtractedToAssets(t *testing.T) {
	// Minimal PNG magic bytes.
	pngMagic := []byte{0x89, 'P', 'N', 'G', 0x0D, 0x0A, 0x1A, 0x0A}
	encoded  := "b64:" + base64.StdEncoding.EncodeToString(pngMagic)

	outDir := t.TempDir()
	windows := []export.WindowExport{
		{Name: "w", Panes: []export.PaneExport{
			{TargetID: "chart", Lines: []string{"before", encoded, "after"}},
		}},
	}

	require.NoError(t, export.Bundle(windows, outDir, "out.md"))

	// Image file must exist in assets/.
	entries, err := os.ReadDir(filepath.Join(outDir, "assets"))
	require.NoError(t, err)
	require.Len(t, entries, 1)
	assert.True(t, strings.HasSuffix(entries[0].Name(), ".png"))

	// Markdown must reference the image.
	data, _ := os.ReadFile(filepath.Join(outDir, "out.md"))
	assert.Contains(t, string(data), "![chart](assets/")
}

func TestBundle_EmptyWindows(t *testing.T) {
	outDir := t.TempDir()
	err := export.Bundle(nil, outDir, "empty.md")
	require.NoError(t, err)
	_, err = os.Stat(filepath.Join(outDir, "empty.md"))
	assert.NoError(t, err)
}

func TestBundle_EmptyLines(t *testing.T) {
	outDir := t.TempDir()
	windows := []export.WindowExport{
		{Name: "w", Panes: []export.PaneExport{{TargetID: "p", Lines: nil}}},
	}
	err := export.Bundle(windows, outDir, "out.md")
	assert.NoError(t, err)
}

func TestBundle_TimestampInHeader(t *testing.T) {
	outDir := t.TempDir()
	require.NoError(t, export.Bundle(nil, outDir, "ts.md"))
	data, _ := os.ReadFile(filepath.Join(outDir, "ts.md"))
	assert.Contains(t, string(data), "Generated by rdw at")
}

func TestBundle_CustomFilename(t *testing.T) {
	outDir := t.TempDir()
	windows := []export.WindowExport{
		{Name: "w", Panes: []export.PaneExport{{TargetID: "p", Lines: []string{"x"}}}},
	}
	require.NoError(t, export.Bundle(windows, outDir, "custom.md"))
	_, err := os.Stat(filepath.Join(outDir, "custom.md"))
	assert.NoError(t, err)
}

// ---------------------------------------------------------------------------
// sniffImageExt via Bundle (indirect coverage)
// ---------------------------------------------------------------------------

func TestBundle_ImageTypes(t *testing.T) {
	// PNG magic bytes
	pngData := []byte{0x89, 'P', 'N', 'G', '\r', '\n', 0x1a, '\n'}
	// JPEG magic bytes
	jpgData := []byte{0xFF, 0xD8, 0xFF, 0xE0}
	// GIF magic bytes
	gifData := []byte("GIF89a\x01\x00\x01\x00")
	// SVG
	svgData := []byte("<svg xmlns=\"http://www.w3.org/2000/svg\"></svg>")
	// Unknown
	binData := []byte{0x00, 0x01, 0x02, 0x03}

	extTests := []struct {
		name    string
		data    []byte
		extWant string
	}{
		{"png", pngData, ".png"},
		{"jpg", jpgData, ".jpg"},
		{"gif", gifData, ".gif"},
		{"svg", svgData, ".svg"},
		{"bin", binData, ".bin"},
	}

	for _, tc := range extTests {
		t.Run(tc.name, func(t *testing.T) {
			b64line := "b64:" + base64.StdEncoding.EncodeToString(tc.data)
			outDir := t.TempDir()

			windows := []export.WindowExport{
				{
					Name: "w",
					Panes: []export.PaneExport{
						{TargetID: "img", Lines: []string{b64line}},
					},
				},
			}

			err := export.Bundle(windows, outDir, "img.md")
			require.NoError(t, err)

			entries, _ := os.ReadDir(filepath.Join(outDir, "assets"))
			found := false
			for _, e := range entries {
				if filepath.Ext(e.Name()) == tc.extWant {
					found = true
					break
				}
			}
			// SVG and known types should produce an asset file.
			if tc.extWant != ".bin" {
				assert.True(t, found, "expected asset with ext %s", tc.extWant)
			}
		})
	}
}
